
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test1
    password: 1234
    url: jdbc:mysql://localhost:3306/springbootwebapp?serverTimezone=UTC&characterEncoding=UTF-8
  jpa:
    hibernate:
      ddl-auto: update
